site_name: Threeport User Documentation
site_author: Qleet Engineering
repo_url: https://github.com/threeport/user-docs
repo_name: threeport/user-docs
edit_uri: blob/main/docs/

nav:
  - Threeport: 'index.md'
  - Guides:
    - 'guides/getting-started.md'
    - 'guides/remote-kubernetes-runtime.md'
    - 'guides/aws-iam.md'
    - 'guides/aws-cross-account-access.md'
  - Architecture:
    - 'Overview': 'architecture/overview.md'
    - 'Tech Stack': 'architecture/tech-stack.md'
    - 'Threeport Controllers': 'architecture/threeport-controllers.md'
    - 'Kubernetes Federation': 'architecture/kubernetes-federation.md'
    - 'Software Delivery': 'architecture/software-delivery.md'
    - 'Orchestration Abstractions': 'architecture/orchestration-abstractions.md'

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/threeport-logo.png
  features:
    - content.code.copy
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
    - search

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/threeport

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: true

copyright: Copyright &copy; 2022-2023 Qleet.io
